name: KeyVault
summary: Deploys Key Vault on ARM
description: Deploys a Key Vault with Private endpoint
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: adminUsername
    name: adminUsername
    description: 'Username'
    type: string
    required: true
  - id: adminPasswordOrKey
    name: adminPasswordOrKey
    description: 'adminPasswordOrKey'
    type: string
    required: true
  - id: workspaceName
    name: workspaceName
    description: 'workspaceName'
    type: string
    required: true    
